from fastapi import FastAPI, HTTPException
import json
import os

app = FastAPI(
    title="IIT Roorkee GMAP API Gateway",
    description="Serves AI-enriched BOQ and embodied carbon metrics for the 3D Box Model viewer.",
    version="1.0.0"
)

# Path to the final enriched pipeline payload generated by your carbon calculator
PAYLOAD_PATH = "gmap_final_enriched_payload.json"

@app.get("/")
def home():
    return {
        "project": "IIT Roorkee GMAP",
        "status": "Active",
        "endpoints": ["/api/v1/boq-data", "/api/v1/summary-carbon"]
    }

@app.get("/api/v1/boq-data")
def get_boq_data():
    """
    Returns the complete structured, classified, and carbon-enriched BOQ dataset.
    """
    if not os.path.exists(PAYLOAD_PATH):
        raise HTTPException(status_code=404, detail="Enriched payload not found. Run the pipeline first!")
        
    with open(PAYLOAD_PATH, "r") as f:
        data = json.load(f)
    return {"total_items": len(data), "items": data}

@app.get("/api/v1/summary-carbon")
def get_carbon_summary():
    """
    Returns the grand total embodied carbon footprint (A1-A3) for the project.
    """
    if not os.path.exists(PAYLOAD_PATH):
        raise HTTPException(status_code=404, detail="Enriched payload not found.")
        
    with open(PAYLOAD_PATH, "r") as f:
        data = json.load(f)
        
    total_carbon = sum(item.get("embodied_carbon_kg_co2e", 0.0) for item in data)
    
    # Category-wise breakdown
    breakdown = {}
    for item in data:
        cat = item.get("material_category", "Unknown")
        breakdown[cat] = breakdown.get(cat, 0.0) + item.get("embodied_carbon_kg_co2e", 0.0)
        
    return {
        "total_embodied_carbon_kg_co2e": round(total_carbon, 2),
        "category_breakdown_kg_co2e": {k: round(v, 2) for k, v in breakdown.items()}
    }

if __name__ == "__main__":
    import uvicorn
    # Launch local development server
    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=True)