from fastapi import FastAPI, HTTPException, File, UploadFile
import json
import os
import shutil

app = FastAPI(
    title="IIT Roorkee GMAP API Gateway",
    description="Serves AI-enriched BOQ and embodied carbon metrics for the 3D Box Model viewer.",
    version="1.0.0"
)

# Path to the final enriched pipeline payload generated by your carbon calculator
PAYLOAD_PATH = "gmap_final_enriched_payload.json"

@app.get("/")
def home():
    return {
        "project": "IIT Roorkee GMAP",
        "status": "Active",
        "endpoints": [
            "/api/v1/boq-data", 
            "/api/v1/summary-carbon",
            "/api/v1/process-boq"
        ]
    }

@app.get("/api/v1/boq-data")
def get_boq_data():
    """
    Returns the complete structured, classified, and carbon-enriched BOQ dataset[cite: 1].
    """
    if not os.path.exists(PAYLOAD_PATH):
        raise HTTPException(status_code=404, detail="Enriched payload not found. Run the pipeline first!")
        
    with open(PAYLOAD_PATH, "r") as f:
        data = json.load(f)
    return {"total_items": len(data), "items": data}

@app.get("/api/v1/summary-carbon")
def get_carbon_summary():
    """
    Returns the grand total embodied carbon footprint (A1-A3) for the project[cite: 1].
    """
    if not os.path.exists(PAYLOAD_PATH):
        raise HTTPException(status_code=404, detail="Enriched payload not found.")
        
    with open(PAYLOAD_PATH, "r") as f:
        data = json.load(f)
        
    total_carbon = sum(item.get("embodied_carbon_kg_co2e", 0.0) for item in data)
    
    # Category-wise breakdown
    breakdown = {}
    for item in data:
        cat = item.get("material_category", "Unknown")
        breakdown[cat] = breakdown.get(cat, 0.0) + item.get("embodied_carbon_kg_co2e", 0.0)
        
    return {
        "total_embodied_carbon_kg_co2e": round(total_carbon, 2),
        "category_breakdown_kg_co2e": {k: round(v, 2) for k, v in breakdown.items()}
    }

@app.post("/api/v1/process-boq")
async def process_uploaded_boq(file: UploadFile = File(...)):
    """
    Accepts a new PDF or Excel BOQ file upload, saves it temporarily, 
    and prepares it to be run through the AI extraction pipeline.
    """
    file_path = f"temp_{file.filename}"
    with open(file_path, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)
    
    try:
        # TODO: Integrate your digital_pdf_engine / ocr_engine and carbon calculator here
        # extracted_data = run_gmap_pipeline(file_path)
        
        return {
            "filename": file.filename,
            "status": "Success",
            "message": "File successfully uploaded and queued for AI parsing and carbon accounting."
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Processing failed: {str(e)}")
    finally:
        # Clean up the temporary file from the server container
        if os.path.exists(file_path):
            os.remove(file_path)

if __name__ == "__main__":
    import uvicorn
    # Launch local development server
    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=True)